/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as PosterRouteImport } from './routes/poster'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicVolunteerRouteImport } from './routes/api/public/volunteer'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterRoute = PosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicVolunteerRoute = ApiPublicVolunteerRouteImport.update({
  id: '/api/public/volunteer',
  path: '/api/public/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/poster': typeof PosterRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/volunteer': typeof ApiPublicVolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/poster': typeof PosterRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/volunteer': typeof ApiPublicVolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/poster': typeof PosterRoute
  '/volunteer': typeof VolunteerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/volunteer': typeof ApiPublicVolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/poster'
    | '/volunteer'
    | '/admin'
    | '/api/public/register'
    | '/api/public/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/poster'
    | '/volunteer'
    | '/admin'
    | '/api/public/register'
    | '/api/public/volunteer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/poster'
    | '/volunteer'
    | '/_authenticated/admin'
    | '/api/public/register'
    | '/api/public/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PosterRoute: typeof PosterRoute
  VolunteerRoute: typeof VolunteerRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
  ApiPublicVolunteerRoute: typeof ApiPublicVolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster': {
      id: '/poster'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/volunteer': {
      id: '/api/public/volunteer'
      path: '/api/public/volunteer'
      fullPath: '/api/public/volunteer'
      preLoaderRoute: typeof ApiPublicVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PosterRoute: PosterRoute,
  VolunteerRoute: VolunteerRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
  ApiPublicVolunteerRoute: ApiPublicVolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
